var Role = {
    Bodyguard: "Bodyguard",
    Doctor: "Doctor",
    Escort: "Escort",
    Investigator: "Investigator",
    Jailor: "Jailor",
    Lookout: "Lookout",
    Mayor: "Mayor",
    Medium: "Medium",
    Retributionist: "Retributionist",
    Sheriff: "Sheriff",
    Spy: "Spy",
    Transporter: "Transporter",
    VampireHunter: "Vampire Hunter",
    Veteran: "Veteran",
    Vigilante: "Vigilante",
    Blackmailer: "Blackmailer",
    Consigliere: "Consigliere",
    Consort: "Consort",
    Disguiser: "Disguiser",
    Forger: "Forger",
    Framer: "Framer",
    Godfather: "Godfather",
    Janitor: "Janitor",
    Mafioso: "Mafioso",
    Amnesiac: "Amnesiac",
    Arsonist: "Arsonist",
    Executioner: "Executioner",
    Jester: "Jester",
    SerialKiller: "Serial Killer",
    Survivor: "Survivor",
    Vampire: "Vampire",
    Werewolf: "Werewolf",
    Witch: "Witch",
    Troll: "Troll"
};

module.exports = Role;
